# Application Name
spring.application.name=nexio-service-discovery

# Eureka Server Port
server.port=8761

# Eureka Server Configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Actuator
management.endpoints.web.exposure.include=health,info